version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: forge
      POSTGRES_DB: forge
    ports:
      - "5432:5432"
    restart: unless-stopped
